resourceMapPath: /mnt/image/
cronQuartStart: false
server:
  port: 99
  tomcat.basedir: /usr/tomcat/tmpfile
apiPath: api
management:
  endpoint:
    mappings:
      enabled: false
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 10MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 100MB
  aop:
    proxy-target-class: true
  application:
    name: eli-main
  #  jpa:
  #    database: MYSQL
  #    hibernate:
  #      ddl-auto: update
  datasource:
    #连接池配置
    ## 初始化大小，最小，最大
    druid:
      url: jdbc:mysql://192.168.101.14:3306/edp_demo?useUnicode=true&characterEncoding=utf-8
      username: edp_demo
      password: edp_demo
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 3
      max-active: 100
      min-idle: 1
      ## 配置获取连接等待超时的时间
      max-wait: 60000
      ## 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #和上面的等价
      max-open-prepared-statements: 20
      validation-query: SELECT 1 FROM t_user
      validation-query-timeout: 300000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      ## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      ## 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 10000000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      #监控配置
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter.enabled: true
      web-stat-filter.url-pattern: /*
      web-stat-filter.exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #spring.datasource.druid.druid.web-stat-filter.session-stat-enable=
      #spring.datasource.druid.druid.web-stat-filter.session-stat-max-count=
      #spring.datasource.druid.druid.web-stat-filter.principal-session-name=
      #spring.datasource.druid.druid.web-stat-filter.principal-cookie-name=
      #spring.datasource.druid.druid.web-stat-filter.profile-enable=
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet.enabled: true
      stat-view-servlet.url-pattern: /druid/*
      stat-view-servlet.reset-enable: false
      stat-view-servlet.login-username: qwe
      stat-view-servlet.login-password: asd
      stat-view-servlet.allow: 192.168.1.101,127.0.0.1
      stat-view-servlet.deny: 192.168.3.12
      ## 下面为连接池的补充设置，应用到上面所有数据源中
      ## 初始化大小，最小，最大
      #spring.datasource.druid.druid.initialSize=5
      #spring.datasource.druid.druid.minIdle=5
      #spring.datasource.druid.druid.maxActive=20
      ## 配置获取连接等待超时的时间
      #spring.datasource.druid.druid.maxWait=60000
      ## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      #spring.datasource.druid.druid.timeBetweenEvictionRunsMillis=60000
      ## 配置一个连接在池中最小生存的时间，单位是毫秒
      #spring.datasource.druid.druid.minEvictableIdleTimeMillis=300000
      #spring.datasource.druid.druid.validationQuery=SELECT 1 FROM t_user
      #spring.datasource.druid.druid.testWhileIdle=true
      #spring.datasource.druid.druid.testOnBorrow=true
      #spring.datasource.druid.druid.testOnReturn=false
      ## 打开PSCache，并且指定每个连接上PSCache的大小
      #spring.datasource.druid.druid.poolPreparedStatements=true
      #spring.datasource.druid.druid.maxPoolPreparedStatementPerConnectionSize=20
      ## 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #spring.datasource.druid.druid.filters=stat,wall,log4j
      ## 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #spring.datasource.druid.druid.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      ## 合并多个DruidDataSource的监控数据
      #spring.datasource.druid.druid.useGlobalDataSourceStat=true

#  thymeleaf:
#    prefix: classpath:/
mybatis:
  #    type-aliases-package: com.lczyfz.entity
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
logging:
  level:
    com.lczyfz : debug
spring.activiti.check-process-definitions: false