package com.lczyfz.demo.sys.mapper;

import com.lczyfz.demo.sys.entity.ExamPaper;
import com.lczyfz.demo.sys.entity.ExamPaperExample;
import java.util.List;

import com.lczyfz.edp.springboot.core.mapper.CrudMapper;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ExamPaperMapper extends CrudMapper<ExamPaper, ExamPaperExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Thu Oct 20 21:29:02 CST 2022
     */
    int countByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Thu Oct 20 21:29:02 CST 2022
     */
    int deleteByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Thu Oct 20 21:29:02 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Thu Oct 20 21:29:02 CST 2022
     */
    int insert(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Thu Oct 20 21:29:02 CST 2022
     */
    int insertSelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Thu Oct 20 21:29:02 CST 2022
     */
    List<ExamPaper> selectByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Thu Oct 20 21:29:02 CST 2022
     */
    ExamPaper selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Thu Oct 20 21:29:02 CST 2022
     */
    int updateByExampleSelective(@Param("record") ExamPaper record, @Param("example") ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Thu Oct 20 21:29:02 CST 2022
     */
    int updateByExample(@Param("record") ExamPaper record, @Param("example") ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Thu Oct 20 21:29:02 CST 2022
     */
    int updateByPrimaryKeySelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Thu Oct 20 21:29:02 CST 2022
     */
    int updateByPrimaryKey(ExamPaper record);
}